### ISSUE TITLE
Look and feel of https://data.ocean-sampling-day.org

### ISSUE THREAD

**Issue by kmexter** [ocean-sampling-day/ocean-sampling-day.github.io#13]
suggested changes to make for https://data.ocean-sampling-day.org/OSD2018/ (and clearly all the other similar folders)
- [ ] in the dark blue left-side menu, the filenames can be long: I'd like to be able to see the full name, perhaps that can pop up when you hover over it with a mouse?
- [ ] the README.md is centre-formatted, please do left-side or even-length-lines formatting
- [ ] The lists in these READMEs are for some reason with a shorter sentence length, could they please instead be just the same as the rest of the text
- [ ] we see that when http's are in the text in the readme, in the github view they come up as links, but not here: can this be fixed or should we instead convert the text to explicitely be links (if that is even possible)?
- [ ] the "i" and the "map" symbol at the top right of all pages, could a popup be used when the mouse is over them to say what they are? i seems to send you back to the README for that folder, the map is a general github search link
- [ ] and instead of being an "all GitHub" search link, can this just be a search in the current space (i.e. OSD here)?
- [ ] on https://data.ocean-sampling-day.org/OSD2018/#./QualityControlledData/ the readme text goes way below the pale blue box it is located in. that should not be

**Comment by cedricdcc** [comment]
this issue will be taken over by https://github.com/vliz-be-opsci/rocrate-to-pages/issues/12
